apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup
  labels:
    runboat/job-kind: cleanup
spec:
  template:
    metadata:
      labels:
        runboat/job-kind: cleanup
    spec:
      enableServiceLinks: false
      containers:
        - name: cleanup
          image: postgres
          volumeMounts:
            - name: runboat-scripts
              mountPath: /runboat
          envFrom:
            - secretRef:
                name: odoosecretenv
            - configMapRef:
                name: odooenv
          args: ["bash", "/runboat/runboat-cleanup.sh"]
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-0o6h4yav8
      volumes:
        - name: runboat-scripts
          configMap:
            name: runboat-scripts
      restartPolicy: Never
  completions: 1
  backoffLimit: 6
